defaults: &defaults
  working_directory: ~/sortify-client
  resource_class: small
  docker:
    - image: circleci/node:lts

version: 2.1
jobs:
  build:
    <<: *defaults
    environment:
      - NODE_ENV: development
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Say hello
          command: echo Hello
      - run:
          name: ls
          command: ls
      - persist_to_workspace:
          root: ~/sortify-client
          path:
            - .
  test:
    <<: *defaults
    steps:
      - attach_to_workspace:
        at: ~/sortify-client
      - run:
          name: ls
          command: ls
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build